# Generated by Django 4.2.30 on 2026-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='units_damaged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
